### ISSUE TITLE
Error when loading a file. 

### ISSUE THREAD

**Issue by otvv** [KN4CK3R/OSHVisualGui#1]
Whenever I try to load a file, I get a parsing error.

"Error while parsing file.xml

ParseError: Font 'Tahoma,8,25,true, false, false' "

It's annoying as fuck to start all over again every time that I open the program.

Here's my GUI.xml file maybe there's something wrong, I don't know. (First day with OSHGui.)
[~snip](https://pastebin.com/1fKzHrAP )

Thanks, Floody.

**Comment by KN4CK3R** [comment]
Thanks for the report. You can restore your file when you change all "8,25" to "8.25" (point instead of comma).
